### ISSUE TITLE
TypeError: wrapper() got an unexpected keyword argument 'username'

### ISSUE THREAD

**Issue by alexandru-grajdeanu** [X1Zeth2X/flask-restx-boilerplate#6]
It looks like there's something wrong when trying to access the `UserGet` resource from Swagger doc page located at `http://127.0.0.1:5000/api/`.

When I remove the `@jwt_required` decorator from the `get()` method it works as expected and  I receive the correct response but as soon as I let it there I get this traceback instead:

```
Traceback (most recent call last):
  File "/Users/alexandrugrajdeanu/Projects/baseapi/venv/lib/python3.8/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/alexandrugrajdeanu/Projects/baseapi/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/alexandrugrajdeanu/Projects/baseapi/venv/lib/python3.8/site-packages/flask_restx/api.py", line 671, in error_router
    return original_handler(f)
  File "/Users/alexandrugrajdeanu/Projects/baseapi/venv/lib/python3.8/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
  File "/Users/alexandrugrajdeanu/Projects/baseapi/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/alexandrugrajdeanu/Projects/baseapi/venv/lib/python3.8/site-packages/flask_restx/api.py", line 669, in error_router
    return self.handle_error(e)
  File "/Users/alexandrugrajdeanu/Projects/baseapi/venv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alexandrugrajdeanu/Projects/baseapi/venv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alexandrugrajdeanu/Projects/baseapi/venv/lib/python3.8/site-packages/flask_restx/api.py", line 671, in error_router
    return original_handler(f)
  File "/Users/alexandrugrajdeanu/Projects/baseapi/venv/lib/python3.8/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
  File "/Users/alexandrugrajdeanu/Projects/baseapi/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/alexandrugrajdeanu/Projects/baseapi/venv/lib/python3.8/site-packages/flask_restx/api.py", line 669, in error_router
    return self.handle_error(e)
  File "/Users/alexandrugrajdeanu/Projects/baseapi/venv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alexandrugrajdeanu/Projects/baseapi/venv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/alexandrugrajdeanu/Projects/baseapi/venv/lib/python3.8/site-packages/flask_restx/api.py", line 403, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/alexandrugrajdeanu/Projects/baseapi/venv/lib/python3.8/site-packages/flask/views.py", line 83, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/alexandrugrajdeanu/Projects/baseapi/venv/lib/python3.8/site-packages/flask_restx/resource.py", line 49, in dispatch_request
    resp = meth(*args, **kwargs)
TypeError: wrapper() got an unexpected keyword argument 'username'
```

The above traceback comes from `controller.py`:

```python

# imports [...]


@api.route("/<string:username>")
class UserGet(Resource):
    @api.doc(
        "Get a specific user",
        responses={
            200: ("User data successfully sent", data_resp),
            404: "User not found!",
        },
    )
    @jwt_required
    def get(self, username):
        """ Get a specific user's data by their username """
        return UserService.get_user_data(username)
```

In order to reproduce this, you can follow the next steps:

* register a user
* login using the above user
* try to access this user's data by making a request to `/api/user/<user>` via Swagger UI.

I suppose this is due to the JWT bearer not being sent along with the request. How can I add that as well in the swagger doc so I can paste it there as well?

**Comment by X1Zeth2X** [comment]
@alexandru-grajdeanu Should work fine now, tests passed.

**Comment by alexandru-grajdeanu** [comment]
That works now.

But you should be aware that requests triggered explicitly from Swagger UI won't work until you add the `Authorization Header` field in the doc. That said, you'll receive:

```json
{
  "msg": "Missing Authorization Header"
}
```

**Comment by unicornlab-zethl** [comment]
> That works now.
> 
> But you should be aware that requests triggered explicitly from Swagger UI won't work until you add the `Authorization Header` field in the doc. That said, you'll receive:
> 
> ```json
> {
>   "msg": "Missing Authorization Header"
> }
> ```

Yes, authorization is required since the user ID is stored inside the JSON Web Token.
Recent versions of Swagger UI allows the usage of Auth headers, but the Swagger provided is from Flask-RestX.
I would just make requests with Postman or other platforms that allow you to call the routes and put headers.
